runtime: nodejs18
env: standard

instance_class: F1  

automatic_scaling:
  min_instances: 0  
  max_instances: 2   
  target_cpu_utilization: 0.65
  target_throughput_utilization: 0.75

handlers:
  - url: /sitemap.xml
    static_files: public/sitemap.xml
    upload: public/sitemap.xml

  - url: /.*
    script: auto 
