runtime: nodejs
env: flex

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 3

resources:
  cpu: 1
  memory_gb: 2
  disk_size_gb: 10

runtime_config:
      operating_system: "ubuntu22"
      runtime_version: "20"



entrypoint: npm start


