main = ".open-next/worker.js"
name = "aerosports-new"
compatibility_date = "2026-06-23"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[observability]
enabled = true

[vars]
NODE_ENV = "production"
NEXT_PUBLIC_BASE_URL = "https://aerosports-new.flat-lab-5831.workers.dev"
NEXT_PUBLIC_API_URL = "https://apis-351216.nn.r.appspot.com/api"
SHEET_URL = "https://docs.google.com/spreadsheets/d/1B_9EaTQDztWGH_cD3lUP7hpWD6FvNBJ-6Czml2x7d9c/export?format=xlsx"
REDIRECT_SHEET_XLSX = "https://docs.google.com/spreadsheets/d/1B_9EaTQDztWGH_cD3lUP7hpWD6FvNBJ-6Czml2x7d9c/export?format=xlsx"
SHEET_CACHE_TTL_SECONDS=86400